### ISSUE TITLE
Release not recognized as a valid source set

### ISSUE THREAD

**Issue by Plastix** [artem-zinnatullin/qualitymatters#129]
For some reason the release code and release unit tests are not recognized by my version of Android studio (2.0-Beta7).

<img width="411" alt="screen shot 2016-03-19 at 12 55 35 pm" src="https://cloud.githubusercontent.com/assets/1526881/13900077/46a3b50c-edd4-11e5-89b9-5a1ec3d9ff48.png">

This makes it impossible to run the release unit tests. I've noticed that the release build type in the gradle config is missing an id. However adding this back in doesn't solve the problem. Any ideas?
```
buildTypes { 
    ...
    release {
            signingConfig signingConfigs.qualityMatters
            applicationIdSuffix '.release' // Missing from build.gradle!!
            ...
    }
```

**Comment by Plastix** [comment]
Apparently you have to switch the build variant in Android studio. It is very strange that Android studio can't view more than one build variant at a time.

**Comment by artem-zinnatullin** [comment]
Yes, in Android Studio you can work only with only one combination of build type and product flavor (qualitymatters doesn't have flavors).

I guess, the main reason why Android Studio has this limitation — because classes from different build types and product flavors may have same fully qualified name, and btw, qualitymatters does have such classes: [`release/../DeveloperSettingsModule.java`](https://github.com/artem-zinnatullin/qualitymatters/blob/7d91c34b3c54ed4268de06f952ff6a238a565de4/app/src/release/java/com/artemzin/qualitymatters/developer_settings/DeveloperSettingsModule.java) and [`debug/../DeveloperSettingsModule.java`](https://github.com/artem-zinnatullin/qualitymatters/blob/7d91c34b3c54ed4268de06f952ff6a238a565de4/app/src/debug/java/com/artemzin/qualitymatters/developer_settings/DeveloperSettingsModule.java)

**Comment by Plastix** [comment]
Thank you for the clarification @artem-zinnatullin!
