### ISSUE TITLE
Switch to Gson with AutoValue-Gson extension

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/qualitymatters#136]
Main reason to use Jackson was the built-in support of builders in Jackson, now we can use Gson which is much smaller (~4x) library with pretty much the same performance.

**Comment by lenguyenthanh** [comment]
:+1: Extractly what I want to do. Another thing is, ObjectMapper takes along time to initialize.

**Comment by artem-zinnatullin** [comment]
Yeah, this is true…

**Comment by lenguyenthanh** [comment]
Let me do a pr for this, tests will be updated too.

**Comment by artem-zinnatullin** [comment]
Sure, I'll be happy to merge such PR!

**Comment by lenguyenthanh** [comment]
Ok, going to do it ;)

**Comment by lenguyenthanh** [comment]
I've switched Gson from Jackson [here](https://github.com/lenguyenthanh/qualitymatters/tree/switch-to-gson-from-jackson). But I think we shouldn't use Gson with AutoValue extension yet. It has several issues:

- It automatically add Gson support for every AutoValue classes. For example it adds Gson support for `AsyncJob` and `ItemsPresenterConfiguration` class. I don't think it is a good idea.

- We need to register our TypeAdapterFactory for each Gson class like: 
````
public Gson provideGson() {
        return new GsonBuilder()
                .registerTypeAdapterFactory(Item.typeAdapterFactory())
                .create();
    }
````

- It doesn't work well with `EqualsVerifier`. All tests about equals and hashCode are failed (`ItemTest`, `AsyncJobTest` and `ItemsPresenterConfigurationTest`). I see that EqualsVerifier cannot read `@NonNull` annotation then it put null value when it verifying so that its throw NPE.

@artem-zinnatullin @vanniktech What do you guys think?

**Comment by vanniktech** [comment]
To be honest I haven't gotten around to use AutoValue and I also never used Gson before. Only Moshi & Jackson.

I'd go for Moshi to be honest since it goes hand in hand with the OkHttpClient. There's also a mosh extension for autovalue.

And as for the 2 class which get Gson support although they should not, maybe there's an annotation on the extension saying hey I don't want this guy to support Gson. If not maybe go and open up a PR there ;)

**Comment by lenguyenthanh** [comment]
I never use Moshi before, it looks nice and fast. Maybe it's time to switch to Moshi :)

Gson AutoValue Extension has only one class file, and it doesn't support any config annotation yet. A PR there is a good idea.

p/s: I've solve second issue with `@JsonAdapter` annotation.

**Comment by vanniktech** [comment]
Yeah we only have one problem that we have some model objects which do have read only fields and we get from the server and we should not send to them. And that behavior right now does not seem to be fully supported in Moshi.

**Comment by lenguyenthanh** [comment]
It's such an important feature, but there're a lot of projects don't need it like this one :smile:

**Comment by artem-zinnatullin** [comment]
>It automatically add Gson support for every AutoValue classes. For example it adds Gson support for AsyncJob and ItemsPresenterConfiguration class. I don't think it is a good idea.

W00t…That's not great.

>We need to register our TypeAdapterFactory for each Gson class like

That's totally fine, because we need attach type adapter to the `gson` instance, I don't see problem here.

>It doesn't work well with EqualsVerifier. All tests about equals and hashCode are failed (ItemTest, AsyncJobTest and ItemsPresenterConfigurationTest). I see that EqualsVerifier cannot read @NonNull annotation then it put null value when it verifying so that its throw NPE

EqualsVerifier is pretty flexible and you can pass some options like nullability support and so on, maybe it's possible to make it work in this case.

------

Regarding Gson/Moshi: until performance is ~ same and if Moshi extension for AutoValue is better — I'm not against using Moshi.

The only preference from me: annotations on each property. I really don't like relying on field/method names because it's implicit. I like when things are explicit and you immediately see things like class is json serializable/parselable.

**Comment by lenguyenthanh** [comment]
`EqualsVerifier is pretty flexible and you can pass some options like nullability support and so on, maybe it's possible to make it work in this case.`
I have tried some way of adding/removing Warning but it doesn't work. Do we have other way to config EqualsVerifier?

About Moshi and Gson, I'll investigate more and give the result back ;)

**Comment by artem-zinnatullin** [comment]
Ah, sad about EqualsVerifier,  I like it.. I don't think I know other ways to configure it

**Comment by lenguyenthanh** [comment]
`It automatically add Gson support for every AutoValue classes. For example it adds Gson support for AsyncJob and ItemsPresenterConfiguration class. I don't think it is a good idea.`
I created an issue for this [here](https://github.com/rharter/auto-value-gson/issues/17). So that we can solve it.

Will try with `Moshi` on this weekend.

**Comment by artem-zinnatullin** [comment]
Great, idk why everybody want `@NoGson`, looks really weird to me.

Really tired of implicit behavior of some langs like Groovy, libs and now annotation processors, makes development painful…

**Comment by lenguyenthanh** [comment]
Yep, I think so too. We need explicit not implicit. Implicit causes a lot of magic bugs.

**Comment by ArazAbishov** [comment]
Starting from autovalue-gson version 0.2.3, it became possible to enable extension only for particular models by specifying factory method which accepts Gson instance as argument. Here is PR which includes implementation with some tests: https://github.com/artem-zinnatullin/qualitymatters/pull/205

**Comment by ArazAbishov** [comment]
Merged into master now: https://github.com/artem-zinnatullin/qualitymatters/pull/205
