### ISSUE TITLE
Code style question

### ISSUE THREAD

**Issue by MrVilkaman** [artem-zinnatullin/qualitymatters#147]
Look at code https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/src/main/java/com/artemzin/qualitymatters/ui/presenters/ItemsPresenter.java#L57

Why you write `items` `error` lambda on new line? it is your code style or it has some practical sense? eg in coverage or debug?

But in other code (in your code) I do not found this style  of code..

eq https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/src/main/java/com/artemzin/qualitymatters/ui/fragments/ItemsFragment.java#L107

**Comment by artem-zinnatullin** [comment]
>Why you write `items` `error` lambda on new line? it is your code style or it has some practical sense? eg in coverage or debug?

Usually I do auto formatting in the IDE and sometimes if lambda is on same line as function where I'm passing it auto formatting adds a lot of left spacing.

I don't have strong opinion on that, unless code doesn't look weird and reads well — I'm ok with that :)

BTW, I'd suggest you to copy links to files from the repo with commit hash, otherwise you link may point to wrong line if we change file in future.
