### ISSUE TITLE
Questions on unit tests

### ISSUE THREAD

**Issue by cxzhang2** [artem-zinnatullin/qualitymatters#183]
1.  Is the hashcode_equals_shouldWorkCorrectly test necessary due to AutoValue?
2.  Looks like we have RunWIth(QualityMattersRobolectricUnitTestRunner.class) in lots of places where Robolectric isn't used?  DeveloperSettingsTest may be the only class that actually takes advantage of Robolectric, can we remove Robolectric entirely by mocking SharedPrefs in that class?

**Comment by vanniktech** [comment]
1. Not 100% sure - though this is not necessary however it does not hurt to have those tests. Could also be that with an update of AutoValue there's a bug (unlikely since they test their lib too) but then the regression would be detected by the CI and you won't have to bother later finding the problem.
2. You need Robolectric when you reference to the Android SDK (basically every import that starts with `android`). Yup mocked sharedprefs is something we want which is also discussed in #53

**Comment by cxzhang2** [comment]
Ah, my mistake on the Robolectric point.  Thanks for the clarification!
