### ISSUE TITLE
What's the point of unbindView?

### ISSUE THREAD

**Issue by cxzhang2** [artem-zinnatullin/qualitymatters#195]
And why have it in onDestroyView vs onDestroy?  The fragment holds the component, which holds the presenter, when the fragment is destroyed the presenter should be automatically eligible for garbage collection no?  Is this just defensive coding or an actual case that we're guarding against?

Follow-up question: what race condition is the `volatile` view guarding against?  What about the previousView == null checks?  I'm having a hard time seeing how either of those exception can be thrown.

Thanks!

**Comment by artem-zinnatullin** [comment]
1. Profit of `unbindView()` in `onDestroyView()` is in ability to retain fragment during configuration change, `onDestroy()` won't be called in that case.
2. `View` is `volatile` because if you do async work in `Presenter` view might be already `unbound` when you'll try to work with it. `volatile` prevents threads from caching reference to `View` and `if (view != null`) will work correctly.

Current MVP setup is not perfect as I would like it to be, hope to find some time to make QualityMatters v2 with much more mature Presenter/ViewModel <-> View interaction model.

Basic idea described here if you interested: https://artemzin.com/blog/rxui-talking-to-android-view-layer-in-a-reactive-way/
