### ISSUE TITLE
Question about AsyncJobsObserver

### ISSUE THREAD

**Issue by david-perez** [artem-zinnatullin/qualitymatters#196]
I'm a little confused about the purpose of [`AsyncJobsObserver`](https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/src/debug/java/com/artemzin/qualitymatters/performance/AsyncJobsObserverImpl.java).

Firstly, is `AsyncJobsObserver`'s sole purpose to track the execution of ongoing concurrent tasks? Does it have any other use besides testing?

Secondly, why is it named like that? Shouldn't it be named `AsyncJobsObservable`/`Subject` ? The way I see it, listeners (tests?) are registered via `addListener()` and notified whenever the number of running `AsyncJob`s changes, so the listeners are the `Observers`, and the number of running `AsyncJobs` is what's being observed. ([Observer pattern](https://en.wikipedia.org/wiki/Observer_pattern))

**Comment by artem-zinnatullin** [comment]
For now it's only for testing, but you can create sort of debug UI and
attach it to observer and see what's going on in the app.

In QualityMatters v2 I'll remove it and won't add until necessary. Tests
will wait for UI conditions instead of async jobs to complete.

And yes, probably Subject is a better term :)
