### ISSUE TITLE
Add fbinfer!

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/qualitymatters#21]

**Comment by vanniktech** [comment]
+1

Never really got it working on my apps

**Comment by TGIO** [comment]
run fbInfer as gradle task maybe ?

**Comment by vanniktech** [comment]
Last time I checked you had to run `./gradlew build` and then pipe the input to the fbinfer script.

**Comment by artem-zinnatullin** [comment]
Yep, I had similar memories. Also, afaik there is no Gradle Plugin at all and you need to have python and download and run fbinfer manually.

**Comment by vanniktech** [comment]
Neither Gradle nor CI plugins. Also setting it up was quite a pain since you had to manually install a thousand of dependencies and so on.

**Comment by vanniktech** [comment]
I just gave it a try again with version 0.6.0 and the set up process became way way better than last time. [Starting point](http://fbinfer.com/docs/getting-started.html)

Unfortunately one has still to install many dependencies, build the infer CL program by hand and set up a couple of other things. At least now when trying to build the program it gives useful errors like hey this dependency is missing and so on.

**Tip:** use `./build-infer.sh java` since we don't care about iOS at this point and you'll save a bit of your sanity.

And once you're done with that you still need to execute it weirdly `infer -- ./gradlew build`

Good thing, it does not find anything on the qualitymattersapp so far:

> Starting analysis (Infer version v0.6.0)
Computing dependencies... 100%
Analyzing 109 clusters.............................................................................................................
Analyzed 687 procedures in 112 files
No issues foun

**Comment by artem-zinnatullin** [comment]
Yay! Nice, thanks for update. Though I still don't want to write scripts to build Infer, it'll require detecting OS and environment..

**Comment by vanniktech** [comment]
Yeah it's nice to run it every once in a while but I don't see how we can automate this into the CI process.

**Comment by vanniktech** [comment]
I just saw that now you can actually install infer with homebrew. That's amazing. No need to build it from their sources ;D

**Comment by artem-zinnatullin** [comment]
Well, I guess homebrew just builds it for you :) But, our CI runs on
Linux..

On Sun, 20 Mar 2016, 00:12 Niklas Baudy, <notifications@github.com> wrote:

> I just saw that now you can actually install infer with homebrew. That's
> amazing. No need to build it from their sources ;D
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/issues/21#issuecomment-198786355>
>
-- 

@artem_zin

**Comment by vanniktech** [comment]
There's also a docker configuration / image available

**Comment by artem-zinnatullin** [comment]
But then you need to install docker for the build..

**Comment by artem-zinnatullin** [comment]
Yo, take a look https://github.com/uber-common/infer-plugin

**Comment by vanniktech** [comment]
Yeah I also just saw it on Twitter. Will check it out in the next days

**Comment by artem-zinnatullin** [comment]
Thanks man, I literally have ~1h for such things per day and spend most of
it on RxJava and other OSS.. I appreciate your help.

**Comment by vanniktech** [comment]
Even though the uber guys have released a [Gradle plugin](https://github.com/uber-common/infer-plugin) for this, setting it up and getting it to work on CI is just too much work.

**Comment by artem-zinnatullin** [comment]
Yeah :(
