### ISSUE TITLE
Add gitter chat

### ISSUE THREAD

**Issue by danielgomezrico** [artem-zinnatullin/qualitymatters#94]
Will be great to have https://gitter.im for this repo so everyone can ask or discuss best practices

**Comment by artem-zinnatullin** [comment]
I'm skeptical to this because knowledge should be searchable (via Google,
etc).

My experience of participating in multiple Gitter and Slack chats is that
everybody ask same things over and over again.

I'd suggest to just create an issue in the repo if you want to discuss
something related to it :)

Or you can join big Slack chat about Android Development
https://androidchat.co

On Tue, 16 Feb 2016, 11:20 Daniel Gomez Rico <notifications@github.com>
wrote:

> Will be great to have https://gitter.im for this repo so everyone can ask
> or discuss best practices
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artem-zinnatullin/qualitymatters/issues/94>.
>
-- 

@artem_zin

**Comment by danielgomezrico** [comment]
:+1: agree
